androidagent: upgrade xamarin.uitest dependency
should fix:
```
 java.lang.RuntimeException: java.util.concurrent.TimeoutException
 at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:49)
 at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:76)
 at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:18)
 at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:51)
 at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
 at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
 at java.lang.Thread.run(Thread.java:841)
 Caused by: java.util.concurrent.TimeoutException
 at java.util.concurrent.FutureTask.get(FutureTask.java:176)
 at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:45)

```